module.exports = {
    helloAPIHandler: require('./helloAPIhandler'),
    registerUserHandler: require('./registerUserHandler'),
    authenticateUserHandler: require('./authenticateUserHandler'),
    registerAdditionalInfoHandler: require('./registerAdditionalInfoHandler'),
    createMealHandler: require('./createMealHandler'),
    retrieveMealsHandler: require('./retrieveMealsHandler'),
    retrieveUserHandler: require('./retrieveUserHandler'),
    retrieveMealHandler: require('./retrieveMealHandler'),
    retrieveOwnMealsHandler: require('./retrieveOwnMealsHandler'),
    updateMealHandler: require('./updateMealHandler'),
    deleteMealHandler: require('./deleteMealHandler'),
    addMealToCartHandler: require('./addMealToCartHandler.js'),
    retrieveCartMealsHandler: require('./retrieveCartMealsHandler'),
    payMealsInCartHandler: require('./payMealsInCartHandler'),
    removeMealFromCartHandler: require('./removeMealFromCartHandler'),
    retrievePendingToPickUpHandler: require('./retrievePendingToPickUpHandler'),
    incrementMealsInCartHandler: require('./incrementMealsInCartHandler'),
    retrievePendingToDeliverHandler: require('./retrievePendingToDeliverHandler'),
    markAsReadyHandler: require('./markAsReadyHandler'),
    retrieveWaitingClientToPickUpHandler: require('./retrieveWaitingClientToPickUpHandler'),
    serverStatusHandler: require('./serverStatusHandler'),
    markAsCompletedHandler: require('./markAsCompletedHandler'),
    searchMealsHandler: require('./searchMealsHandler'),
    toggleLikeChefHandler: require('./toggleLikeChefHandler'),
    retrieveLikedChefsHandler: require('./retrieveLikedChefsHandler')
}